### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by codler** [ilkkarinne/covidjson#1]
https://github.com/spatineo/covidjson/blob/master/data.covidjson.org/converter/src/main/resources/templates/totalInfectionCount.geojson?short_path=3602317#L14

`procedureReference` and `observedProperty` in template have broken link.

**Comment by ilkkarinne** [comment]
Indeed, content for the procedure and observedProperty have not been created for this demo application. In a real-world example these would point to the external resources describing the process and the observedProperty used.

The observedProperty would in most cases point to an external code list value defining the observed property, but it could also be a JSON/RDF resource with more details.  The procedure would in most cases be a textual description of the process steps followed, so it could just be a web page, or in other cases a machine-readable resource.

I agree that even for a demonstrator, the links should resolve into something. I'll put this on my todo list.
